// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace BDS_MLML.Model
{
    public class ModelInput
    {
        [ColumnName("size"), LoadColumn(0)]
        public float Size { get; set; }


        [ColumnName("floor"), LoadColumn(1)]
        public float Floor { get; set; }


        [ColumnName("bedroom"), LoadColumn(2)]
        public float Bedroom { get; set; }


        [ColumnName("bathroom"), LoadColumn(3)]
        public float Bathroom { get; set; }


        [ColumnName("yard"), LoadColumn(4)]
        public float Yard { get; set; }


        [ColumnName("price"), LoadColumn(5)]
        public float Price { get; set; }


    }
}
